Repository kendryte/k510_buildroot, pull requests merged in 2022-11, with the labels that each got.

#368 Fix encode_app 1080x1920 shows abnormal
  package/encode_app/src/main.cpp
  package/venc_lib/src/libvenc.so
Labels: bug

#377 add imx385 conf install cmd
  package/encode_app/encode_app.mk
Labels: feature

#380 alsa aplay plays dual channel 32-bit sampled audio, only one channel can hear the sound
  package/encode_app/src/main.cpp
  package/patches/linux/0037-nau8822-capture-mixaudio-32bit.patch
Labels: bug

#383 fix #382, set IO 115 pin 3.3V
  package/patches/linux/0037-Fix-UART1RX-IO-voltage-set-to-3.3V.patch
Labels: bug

#384 modify gc2093conf and disable color2BW
  package/ai/code/gc2093.conf
  package/encode_app/encode_app.mk
  package/encode_app/src/gc2093.conf
  package/encode_app/src/video_drm_gc2093_gc2053_isp_mux.conf
  package/mediactl_lib/src/adaptive/sensor_params/gc2093_gc2053/adaptive_gc2093_f2k.h
  package/mediactl_lib/src/config/gc2093.conf
  package/mediactl_lib/src/config/video_drm_gc2093_gc2053_isp_mux.conf
Labels: feature

#372 emmc and nand boot cmd modify
  board/canaan/k510/uboot-emmc.env
  board/canaan/k510/uboot-nand.env
Labels: bug

#388 fix #386, face_recog demo share memory leak
  package/ai/code/face_recog/insightface.cc
  package/ai/code/face_recog/main.cc
  package/ai/code/face_recog/retinaface.cc
Labels: bug

#389 modif exposure setting and conf of sc053hgs
  package/mediactl_lib/src/config/sc035hgs.conf
  package/patches/linux/0039-modify-exposure-setting-of-sc035hgs.patch
Labels: feature

#394 The number of temperature sensors that read the temperature was reduc…
  package/patches/linux/0040-The-number-of-temperature-sensors-that-read-the-temp.patch
Labels: bug

#396 add ir cut user API
  package/mediactl_lib/src/adaptive/adaptive_setting.h
  package/mediactl_lib/src/adaptive/adaptive_user_func.h
  package/mediactl_lib/src/adaptive/sensor_params/canaan_isp_struct.h
  package/mediactl_lib/src/libadaptive.so
  package/mediactl_lib/src/media_ctl.c
  package/mediactl_lib/src/media_ctl.h
Labels: bug, feature

#398 Fix ffmpeg shram alloc error
  package/ffmpeg_canaan/0036-buildroot-ffmpeg.patch
Labels: bug
