Repository kendryte/k510_buildroot, pull requests merged in 2022-07, with the labels that each got.

#166 ffmpeg: correct frame rate tiny adjust
  package/ffmpeg_canaan/0028-buildroot-ffmpeg.patch
Labels: bug

#173 github actions add test job
  .github/workflows/build.yml
Labels: feature

#176 Fix linux crash when booting
  package/patches/linux/0013-Modify-l2-tag-data-ram-ctl-to-1.patch
  package/riscv-pk-k510/riscv-pk-k510.mk
Labels: bug

#169 fix #167, remove v4l2_drm -v argument
  package/mediactl_lib/src/v4l2_drm/v4l2_drm.c
Labels: bug

#178 fix #177, dual camera AE
  package/mediactl_lib/src/media_ctl.c
  package/mediactl_lib/src/media_ctl.h
  package/mediactl_lib/src/v4l2_drm/v4l2_drm.c
  package/patches/linux/0007-k510-isp-driver-repeated-free-memory.patch
  package/patches/linux/0013-add-ISP-AE-device.patch
  package/patches/uboot/0005-increase-FPS.patch
Labels: bug

#180 fix #179, v4l2_drm_isptool on camera 1
  package/mediactl_lib/src/v4l2_drm_isptool/v4l2_drm_isptool.c
Labels: bug

#185 Fix vi double start
  package/mediactl_lib/src/v4l2_drm/v4l2_drm.c
  package/patches/linux/0014-fix-vi-double-start.patch
Labels: bug

#189 Improve isp reset
  package/patches/linux/0015-isp-reset.patch
Labels: bug

#193 Add feature:build k510-hdmi.dtb to image file
  board/canaan/k510/genimage-emmc.cfg
  board/canaan/k510/genimage-sdcard.cfg
  board/canaan/k510/post-image-crb_v1_2.sh
Labels: feature

#190 modify AE default setting and gamma table
  package/patches/linux/0016-modify-AE-default-setting-and-gamma-table.patch
Labels: feature

#197 fix AE slow and bounce
  package/isp-tuningd/src/isp-tuningd.c
  package/mediactl_lib/src/config/imx219_0.conf
  package/mediactl_lib/src/config/imx219_1.conf
  package/mediactl_lib/src/config/imx219_1080x1920_0.conf
  package/mediactl_lib/src/config/imx219_1080x1920_1.conf
  package/mediactl_lib/src/media_ctl.c
  package/patches/linux/0017-fix-imx219-gain-and-exposure-parameter-settings.patch
Labels: bug

#198 Improve Jpeg encode quality
  package/encode_app/src/main.cpp
  package/venc_lib/src/enc_interface.h
  package/venc_lib/src/libvenc.so
Labels: bug

#203 Encode app frc control
  package/encode_app/src/main.cpp
Labels: feature

#201 add IMX385 config file and update IMX385 ae calc accuracy
  package/encode_app/encode_app.mk
  package/encode_app/src/imx385_0.conf
  package/encode_app/src/imx385_video_1920x1080.conf
  package/mediactl_lib/src/config/imx385_0.conf
  package/mediactl_lib/src/config/imx385_video_1920x1080.conf
  package/patches/linux/0018-update-imx385-ae-calc-accuracy.patch
Labels: feature

#206 fix #205, isp-tuningd h264 error
  package/isp-tuningd/src/isp-tuningd.c
Labels: bug

#210 improve color accuracy
  package/encode_app/src/imx219_0.conf
  package/encode_app/src/imx219_1.conf
  package/mediactl_lib/src/config/imx219_0.conf
  package/mediactl_lib/src/config/imx219_1.conf
  package/mediactl_lib/src/config/imx219_1080x1920_0.conf
  package/mediactl_lib/src/config/imx219_1080x1920_1.conf
Labels: feature

#223 ISP: Remove wrong alignment for image size
  package/patches/linux/0019-fix-isp-image-size-align.patch
Labels: bug

#225 fix ffmpeg audio3a invalidate failure
  package/ffmpeg_canaan/0029-buildroot-ffmpeg.patch
Labels: bug

#221 fix #220, read a bunch frames before display
  package/mediactl_lib/src/v4l2_drm/v4l2_drm.cc
Labels: bug

#229 enable logo and init ws2812
  package/patches/linux/0020-fix-vo-driver.patch
  package/patches/uboot/0007-enable-logo-display.patch
  package/patches/uboot/0008-add-ws2812-init.patch
Labels: bug

#237 fix hdmi double dispaly and reopen uboot v5l2_cache
  package/mediactl_lib/src/v4l2_drm/v4l2_drm.cc
  package/patches/uboot/0008-add-ws2812-init.patch
Labels: bug

#227 Update README.md
  README.md
Labels: documentation

#239 fix rtc-kendryte code error , sd bootcmd modify to loop, lcd id read fialed reboot board
  board/canaan/k510/uboot-sdcard.env
  package/patches/linux/0021-fix-kendryte-rtc-driver-code-error.patch
  package/patches/uboot/0009-uboot-lcd-init-faile-reboot-board.patch
Labels: bug

#241 fix #240, add NONBLOCK flag to mono camera program
  package/mediactl_lib/src/v4l2_drm/drm/k510_drm.c
Labels: bug

#243 Fix ISP outputs right column garbage
  package/mediactl_lib/src/isp/json_parse.c
Labels: bug

#255 Fix cpu2dsp app running failed
  package/dsp_scheduler/src/tasks/sample_task.c
Labels: bug

#254 Fix encode app default output framerate
  package/encode_app/src/main.cpp
Labels: bug

#247 nncase update to v1.7.1
  Makefile
  package/nncase_linux_runtime/nncase_linux_runtime.hash
  package/nncase_linux_runtime/nncase_linux_runtime.mk
Labels: feature

#257 Ffmpeg pushes RTMP with error conversion failed
  package/ffmpeg_canaan/0031-buildroot-ffmpeg.patch
Labels: bug

#260 fix lcd logo bug
  board/canaan/k510/k510_rootfs_skeleton/etc/uboot_dsi_logo.gbr.bmp.argb
  package/patches/linux/0022-fix-vo-driver.patch
  package/patches/uboot/0010-enable-lcd-logo.patch
Labels: bug
