Repository kendryte/k510_buildroot, pull requests merged in 2022-05, with the labels that each got.

#4 nncase update to v1.6.0
  Makefile
  package/nncase_linux_runtime/nncase_linux_runtime.hash
  package/nncase_linux_runtime/nncase_linux_runtime.mk
Labels: enhancement

#7 add CONTRIBUTING, issue and PR template
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/help.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/pull_request_template.md
  README.md
Labels: feature

#11 nncase k510 update to v1.6.1
  Makefile
  package/nncase_linux_runtime/nncase_linux_runtime.hash
  package/nncase_linux_runtime/nncase_linux_runtime.mk
Labels: feature

#14 Improve ISP spilt screen
  package/mediactl_lib/src/v4l2_drm/v4l2_drm.c
  package/patches/linux/0003-isp-dma.patch
Labels: bug

#16 Add coding parameters and advanced functions
  package/encode_app/encode_app.mk
  package/encode_app/src/main.cpp
  package/encode_app/src/roi_1920x1080.conf
  package/patches/linux/0004-tcperror-canaan-20220513.patch
  package/venc_lib/src/enc_interface.h
  package/venc_lib/src/libvenc.so
Labels: feature

#23 fix README.md
  README.md
Labels: documentation

#31 To support multi-format sensor input
  package/encode_app/src/video_sample_720p60.conf
  package/encode_app/src/video_sample_vga480p75.conf
  package/patches/linux/0006-sensor-fr.patch
Labels: feature

#33 To add 720p60 & vga@75fps configure files
  package/encode_app/encode_app.mk
Labels: feature

#35 Ffmpeg K510 coding exception
  package/ffmpeg_canaan/0020-buildroot-ffmpeg.patch
Labels: bug

#39 open f-2k ae, open r-2k ae
  package/mediactl_lib/src/v4l2_drm/v4l2_drm.c
Labels: bug

#45 ffmpeg encodes JEPG, press Q to exit core dump
  package/venc_lib/src/enc_interface.h
  package/venc_lib/src/libvenc.so
Labels: bug

#50 在开机脚本中增加 ae 单摄打开
  board/canaan/k510/k510_rootfs_skeleton/etc/init.d/rc.sysinit
Labels: bug

#52 improve AE speed
  package/mediactl_lib/src/v4l2_drm/imx219_1080x1920_0.conf
Labels: feature

#47 [Feature & BugFix]: isp-tuningd
  Config.in
  configs/k510_crb_lp3_v0_1_defconfig
  configs/k510_crb_lp3_v1_2_defconfig
  package/isp-tuningd/Config.in
  package/isp-tuningd/isp-tuningd.mk
  package/isp-tuningd/src/Makefile
  package/isp-tuningd/src/isp-tuningd.c
  package/mediactl_lib/Config.in
  package/mediactl_lib/mediactl_lib.mk
  package/mediactl_lib/src/v4l2_drm_isptool/Makefile
Labels: bug, feature

#58 Fix #57, incomplete/broken images when ISP Tuning Tool is paused and replayed
  package/isp-tuningd/src/isp-tuningd.c
Labels: bug

#60 adjust ae speed
  package/mediactl_lib/src/v4l2_drm/imx219_1080x1920_0.conf
Labels: feature

#67 Add coding functions: Deblocking，slice, entropy coding, SEI
  package/encode_app/src/main.cpp
  package/ffmpeg_canaan/0022-buildroot-ffmpeg.patch
  package/venc_lib/src/enc_interface.h
  package/venc_lib/src/libvenc.so
Labels: feature

#71 Modify SEI user data implementation
  package/venc_lib/src/libvenc.so
Labels: feature

#76 Encode_ App, set 7 or 8 ROIs, and start the core dump
  package/venc_lib/src/libvenc.so
Labels: bug

#74 fix ffmpeg parser error, fix alloc error
  package/encode_app/src/main.cpp
  package/ffmpeg_canaan/0023-buildroot-ffmpeg.patch
  package/patches/linux/0007-share-memory-align-alloc.patch
Labels: bug

#83 encode_app add audio G.711 encoding and pushes RTSP stream
  package/encode_app/src/G711Codec.cpp
  package/encode_app/src/G711Codec.h
  package/encode_app/src/Makefile
  package/encode_app/src/main.cpp
  package/live555_canaan/0007-buildroot-live555.patch
Labels: feature

#86 There are too many configuration files in the v4l2 demo, which cannot be managed uniformly
  package/mediactl_lib/mediactl_lib.mk
  package/mediactl_lib/src/config/imx219_0.conf
  package/mediactl_lib/src/config/imx219_1.conf
  package/mediactl_lib/src/config/imx219_1080x1920_0.conf
  package/mediactl_lib/src/config/video_drm_1080x1920.conf
  package/mediactl_lib/src/config/video_drm_1080x1920_r2k.conf
  package/mediactl_lib/src/config/video_drm_1920x1080.conf
  package/mediactl_lib/src/v4l2_demo/video.conf
  package/mediactl_lib/src/v4l2_drm/imx219_0.conf
  package/mediactl_lib/src/v4l2_drm/imx219_1.conf
Labels: bug

#78 fix k510 isp driver repeated free memory
  package/patches/linux/0007-k510-isp-driver-repeated-free-memory.patch
Labels: bug

#81 isp-tuningd: add param to enable/disable JPEG codec
  package/isp-tuningd/src/isp-tuningd.c
  package/mediactl_lib/src/v4l2_drm_isptool/v4l2_drm_isptool.c
Labels: feature

#63 fix: #62, ISP Tuning Tool add 3DNR & LDC
  package/mediactl_lib/src/isp/isp_cfg.c
  package/mediactl_lib/src/media_ctl.c
Labels: feature

#87 improve image quality
  package/encode_app/src/imx219_0.conf
  package/encode_app/src/imx219_1.conf
  package/mediactl_lib/src/config/imx219_0.conf
  package/mediactl_lib/src/config/imx219_1.conf
  package/mediactl_lib/src/config/imx219_1080x1920_0.conf
  package/mediactl_lib/src/config/video_drm_1080x1920.conf
  package/mediactl_lib/src/config/video_drm_1080x1920_r2k.conf
  package/mediactl_lib/src/media_ctl.c
  package/mediactl_lib/src/media_ctl.h
Labels: feature

#90 gamma calibration & reduce image sensor clock frequency
  package/patches/linux/0008-gamma-calibration-and-reduce-image-sensor-clock-freq.patch
Labels: feature

#89 add ae control in encode app
  package/encode_app/src/main.cpp
Labels: feature
